@echo off
echo Starting Slang Language Detection App...
echo Starting FastAPI Backend...
start cmd /k ".\venv\Scripts\activate.bat && uvicorn api:app --host 0.0.0.0 --port 8000"

echo Waiting 5 seconds for backend to start...
timeout /t 5 /nobreak

echo Starting Streamlit Frontend...
start cmd /k ".\venv\Scripts\activate.bat && streamlit run app.py"

echo Both services are now running!
